### ISSUE TITLE
[BUG]: AttributeError: module 'dspy' has no attribute 'AzureOpenAI'

### ISSUE THREAD

**Issue by hasalams** [Neoxelox/dspy-inspector#3]
### Impact

Hinder: It obstructs me to do what I want

### Description

I am using `dspy.AzureOpenAI` with `dspy-ai-2.4.0` There's a conflict with the specified version in the toml file 

`dspy-ai = "2.1.10"`
Error: `AttributeError: module 'dspy' has no attribute 'AzureOpenAI'`

Please update the dspy-ai version in the toml file. Thank you.

### Steps To Reproduce

In your terminal:

```bash 
pip install dspy-ai
pip install dspy-inspector
```

Run Python code:
```python
import dspy

api_key = 'api-key'
base = 'api-base'
engine = 'gpt-4'
version = '2024-02-15-preview'

llm = dspy.AzureOpenAI(model=engine, api_key=api_key, api_base=base, api_version=version, model_type="chat")

dspy.settings.configure(lm=llm)
```

**Comment by neoxelox** [comment]
Hi @hasalams thanks for your time and interest.

I can update the DSPy dependency if you need it. However, notice that (as said in the readme), DSPy is going through a big refactor at this moment, and I stopped working on the inspector until a more stable version is released. That means that the parsing logic to build the graph is probably broken.

If you need a tool to have some observability into your pipelines I recommend you https://github.com/Arize-ai/phoenix :
Packages:
```plain
arize-phoenix=="3.18.1"
openinference-instrumentation-dspy=="0.1.6"
opentelemetry-exporter-otlp=="1.23.0"
opentelemetry-sdk=="1.23.0"
```

Example code:
```python
import phoenix
from openinference.instrumentation.dspy import DSPyInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import SimpleSpanProcessor

phoenix.launch_app(host="localhost", port=6006)
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(span_exporter=OTLPSpanExporter(endpoint="http://localhost:6006/v1/traces")))
trace_api.set_tracer_provider(tracer_provider=tracer_provider)
DSPyInstrumentor().instrument()
```

Then you can access a web UI in http://localhost:6006 and you will see automatically all your LLM calls.

Nevertheless, if you really need me to update the DSPy version, please don't hesitate telling me. Thanks.

**Comment by hasalams** [comment]
> Hi @hasalams thanks for your time and interest.
> 
> I can update the DSPy dependency if you need it. However, notice that (as said in the readme), DSPy is going through a big refactor at this moment, and I stopped working on the inspector until a more stable version is released. That means that the parsing logic to build the graph is probably broken.
> 
> If you need a tool to have some observability into your pipelines I recommend you https://github.com/Arize-ai/phoenix : Packages:
> 
> ```
> arize-phoenix=="3.18.1"
> openinference-instrumentation-dspy=="0.1.6"
> opentelemetry-exporter-otlp=="1.23.0"
> opentelemetry-sdk=="1.23.0"
> ```
> 
> Example code:
> 
> ```python
> import phoenix
> from openinference.instrumentation.dspy import DSPyInstrumentor
> from opentelemetry import trace as trace_api
> from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
> from opentelemetry.sdk import trace as trace_sdk
> from opentelemetry.sdk.trace.export import SimpleSpanProcessor
> 
> phoenix.launch_app(host="localhost", port=6006)
> tracer_provider = trace_sdk.TracerProvider()
> tracer_provider.add_span_processor(SimpleSpanProcessor(span_exporter=OTLPSpanExporter(endpoint="http://localhost:6006/v1/traces")))
> trace_api.set_tracer_provider(tracer_provider=tracer_provider)
> DSPyInstrumentor().instrument()
> ```
> 
> Then you can access a web UI in http://localhost:6006 and you will see automatically all your LLM calls.
> 
> Nevertheless, if you really need me to update the DSPy version, please don't hesitate telling me. Thanks.

Thanks for the suggestion and the sample code. This helps me to understand what happens behind the scene in my DSPy pipeline. Please do update if you do further changes to your library. The graphical visualisation is really useful. Keep up the good work. Cheers!
